// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mydata.proto

package tutorial

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TreeData struct {
	Dim                  int32    `protobuf:"varint,1,opt,name=Dim,proto3" json:"Dim,omitempty"`
	MinChildren          int32    `protobuf:"varint,2,opt,name=MinChildren,proto3" json:"MinChildren,omitempty"`
	MaxChildren          int32    `protobuf:"varint,3,opt,name=MaxChildren,proto3" json:"MaxChildren,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	Size                 int32    `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	NSlices              float64  `protobuf:"fixed64,6,opt,name=NSlices,proto3" json:"NSlices,omitempty"`
	NSubtree             float64  `protobuf:"fixed64,7,opt,name=NSubtree,proto3" json:"NSubtree,omitempty"`
	MyEntries            []*Entry `protobuf:"bytes,8,rep,name=MyEntries,proto3" json:"MyEntries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreeData) Reset()         { *m = TreeData{} }
func (m *TreeData) String() string { return proto.CompactTextString(m) }
func (*TreeData) ProtoMessage()    {}
func (*TreeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_90b11ecd0230d6a3, []int{0}
}

func (m *TreeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeData.Unmarshal(m, b)
}
func (m *TreeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeData.Marshal(b, m, deterministic)
}
func (m *TreeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeData.Merge(m, src)
}
func (m *TreeData) XXX_Size() int {
	return xxx_messageInfo_TreeData.Size(m)
}
func (m *TreeData) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeData.DiscardUnknown(m)
}

var xxx_messageInfo_TreeData proto.InternalMessageInfo

func (m *TreeData) GetDim() int32 {
	if m != nil {
		return m.Dim
	}
	return 0
}

func (m *TreeData) GetMinChildren() int32 {
	if m != nil {
		return m.MinChildren
	}
	return 0
}

func (m *TreeData) GetMaxChildren() int32 {
	if m != nil {
		return m.MaxChildren
	}
	return 0
}

func (m *TreeData) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TreeData) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TreeData) GetNSlices() float64 {
	if m != nil {
		return m.NSlices
	}
	return 0
}

func (m *TreeData) GetNSubtree() float64 {
	if m != nil {
		return m.NSubtree
	}
	return 0
}

func (m *TreeData) GetMyEntries() []*Entry {
	if m != nil {
		return m.MyEntries
	}
	return nil
}

type Rect struct {
	P                    []float64 `protobuf:"fixed64,1,rep,packed,name=P,proto3" json:"P,omitempty"`
	Q                    []float64 `protobuf:"fixed64,2,rep,packed,name=Q,proto3" json:"Q,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Rect) Reset()         { *m = Rect{} }
func (m *Rect) String() string { return proto.CompactTextString(m) }
func (*Rect) ProtoMessage()    {}
func (*Rect) Descriptor() ([]byte, []int) {
	return fileDescriptor_90b11ecd0230d6a3, []int{1}
}

func (m *Rect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rect.Unmarshal(m, b)
}
func (m *Rect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rect.Marshal(b, m, deterministic)
}
func (m *Rect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rect.Merge(m, src)
}
func (m *Rect) XXX_Size() int {
	return xxx_messageInfo_Rect.Size(m)
}
func (m *Rect) XXX_DiscardUnknown() {
	xxx_messageInfo_Rect.DiscardUnknown(m)
}

var xxx_messageInfo_Rect proto.InternalMessageInfo

func (m *Rect) GetP() []float64 {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *Rect) GetQ() []float64 {
	if m != nil {
		return m.Q
	}
	return nil
}

type Entry struct {
	Bb                   *Rect    `protobuf:"bytes,1,opt,name=Bb,proto3" json:"Bb,omitempty"`
	Obj                  *any.Any `protobuf:"bytes,2,opt,name=Obj,proto3" json:"Obj,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_90b11ecd0230d6a3, []int{2}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetBb() *Rect {
	if m != nil {
		return m.Bb
	}
	return nil
}

func (m *Entry) GetObj() *any.Any {
	if m != nil {
		return m.Obj
	}
	return nil
}

type Thing struct {
	Location             []float64 `protobuf:"fixed64,1,rep,packed,name=Location,proto3" json:"Location,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Thing) Reset()         { *m = Thing{} }
func (m *Thing) String() string { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()    {}
func (*Thing) Descriptor() ([]byte, []int) {
	return fileDescriptor_90b11ecd0230d6a3, []int{3}
}

func (m *Thing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thing.Unmarshal(m, b)
}
func (m *Thing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thing.Marshal(b, m, deterministic)
}
func (m *Thing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thing.Merge(m, src)
}
func (m *Thing) XXX_Size() int {
	return xxx_messageInfo_Thing.Size(m)
}
func (m *Thing) XXX_DiscardUnknown() {
	xxx_messageInfo_Thing.DiscardUnknown(m)
}

var xxx_messageInfo_Thing proto.InternalMessageInfo

func (m *Thing) GetLocation() []float64 {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Thing) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*TreeData)(nil), "tutorial.TreeData")
	proto.RegisterType((*Rect)(nil), "tutorial.Rect")
	proto.RegisterType((*Entry)(nil), "tutorial.Entry")
	proto.RegisterType((*Thing)(nil), "tutorial.Thing")
}

func init() { proto.RegisterFile("mydata.proto", fileDescriptor_90b11ecd0230d6a3) }

var fileDescriptor_90b11ecd0230d6a3 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x5f, 0x4f, 0xf2, 0x30,
	0x18, 0xc5, 0xd3, 0x8d, 0xc1, 0x78, 0x46, 0xde, 0xd7, 0x34, 0xc6, 0x54, 0x2e, 0x74, 0xd9, 0x85,
	0xd9, 0x8d, 0x23, 0xc1, 0x0b, 0xaf, 0x45, 0x4c, 0xbc, 0x90, 0x7f, 0x85, 0x2f, 0xd0, 0x41, 0x1d,
	0x35, 0x5b, 0x4b, 0x46, 0x49, 0x9c, 0xdf, 0xda, 0x6f, 0x60, 0xda, 0x01, 0x33, 0xde, 0x3d, 0xe7,
	0x9c, 0xdf, 0xce, 0xd2, 0x03, 0xbd, 0xa2, 0xda, 0x30, 0xcd, 0x92, 0x5d, 0xa9, 0xb4, 0xc2, 0xbe,
	0x3e, 0x68, 0x55, 0x0a, 0x96, 0xf7, 0x6f, 0x33, 0xa5, 0xb2, 0x9c, 0x0f, 0xac, 0x9f, 0x1e, 0xde,
	0x07, 0x5a, 0x14, 0x7c, 0xaf, 0x59, 0xb1, 0xab, 0xd1, 0xfe, 0xf5, 0x5f, 0x80, 0xc9, 0xaa, 0x8e,
	0xa2, 0x6f, 0x04, 0xfe, 0xaa, 0xe4, 0x7c, 0xcc, 0x34, 0xc3, 0x17, 0xe0, 0x8e, 0x45, 0x41, 0x50,
	0x88, 0x62, 0x8f, 0x9a, 0x13, 0x87, 0x10, 0x4c, 0x84, 0x7c, 0xde, 0x8a, 0x7c, 0x53, 0x72, 0x49,
	0x1c, 0x9b, 0xfc, 0xb6, 0x2c, 0xc1, 0x3e, 0xcf, 0x84, 0x7b, 0x24, 0x1a, 0x0b, 0x5f, 0x41, 0xfb,
	0x95, 0x8b, 0x6c, 0xab, 0x49, 0xcb, 0x86, 0x47, 0x85, 0x31, 0xb4, 0x96, 0xe2, 0x8b, 0x13, 0xcf,
	0xba, 0xf6, 0xc6, 0x04, 0x3a, 0xd3, 0x65, 0x2e, 0xd6, 0x7c, 0x4f, 0xda, 0x21, 0x8a, 0x11, 0x3d,
	0x49, 0xdc, 0x07, 0x7f, 0xba, 0x3c, 0xa4, 0xba, 0xe4, 0x9c, 0x74, 0x6c, 0x74, 0xd6, 0xf8, 0x1e,
	0xba, 0x93, 0xea, 0x45, 0xea, 0x52, 0xf0, 0x3d, 0xf1, 0x43, 0x37, 0x0e, 0x86, 0xff, 0x93, 0xd3,
	0x3c, 0x89, 0x09, 0x2a, 0xda, 0x10, 0x51, 0x04, 0x2d, 0xca, 0xd7, 0x1a, 0xf7, 0x00, 0xcd, 0x09,
	0x0a, 0xdd, 0x18, 0x51, 0x34, 0x37, 0x6a, 0x41, 0x9c, 0x5a, 0x2d, 0xa2, 0x19, 0x78, 0xf6, 0x3b,
	0x7c, 0x03, 0xce, 0x28, 0xb5, 0x93, 0x04, 0xc3, 0x7f, 0x4d, 0xa9, 0x29, 0xa0, 0xce, 0x28, 0xc5,
	0x77, 0xe0, 0xce, 0xd2, 0x0f, 0xbb, 0x4c, 0x30, 0xbc, 0x4c, 0xea, 0xa5, 0x93, 0xd3, 0xd2, 0xc9,
	0x93, 0xac, 0xa8, 0x01, 0xa2, 0x47, 0xf0, 0x56, 0x5b, 0x21, 0x33, 0xf3, 0x90, 0x37, 0xb5, 0x66,
	0x5a, 0x28, 0x79, 0xfc, 0xf9, 0x59, 0x9b, 0x49, 0xa6, 0xac, 0xe0, 0xb6, 0xad, 0x4b, 0xed, 0x9d,
	0xb6, 0x6d, 0xd7, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x0b, 0x11, 0x65, 0xfe, 0x01,
	0x00, 0x00,
}
